apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-d-inference-gateway
  labels:
    app.kubernetes.io/gateway: llm-d-inference-gateway
    app.kubernetes.io/component: inference-gateway
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            command:
              - /bin/sh
              - -c
            args:
              - |-
                ulimit -n 65536 && \
                /usr/local/bin/pilot-agent proxy router \
                --domain $(POD_NAMESPACE).svc.cluster.local \
                --proxyLogLevel=warn \
                --proxyComponentLogLevel=misc:warn \
                --log_output_level=default:warn

            resources:
              limits:
                cpu: "8"
                memory: 16Gi
              requests:
                cpu: 2
                memory: 4Gi
            # Note (varun): Required for ulimit setting
            securityContext:
              privileged: true
              allowPrivilegeEscalation: true
              runAsNonRoot: false
              runAsUser: 0
              capabilities:
                drop: []
  service: |
    spec:
      type: LoadBalancer
