apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-guidellm
  labels:
    app: guide-llm
spec:
  parallelism: ${N_WORKERS}
  completions: ${N_WORKERS}
  completionMode: Indexed
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: poker
    spec:
      affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - poker
              topologyKey: "kubernetes.io/hostname"
      restartPolicy: Never
      tolerations:
      # (varun) This allows the pod to be placed in a node with
      # a GPU. If I dont do this, then kubernetes can't find machine.
      # Maybe there is a better way.
      - key: "amd.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: poker
          #image: quay.io/tms/poker:0.0.10
          image: quay.io/rh-ee-vsundarr/poker:oci
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "4"
              memory: "64Gi"

          command: ["/bin/bash","-c"]
          args:
            - |
              # These are poorly behaved.
              #  --warmup-percent "0.20" \
              #  --cooldown-percent "0.20" \
              
              mkdir -p /guide-llm/${OUTPUT_PATH}

              # For experiment tracking
              echo "GUIDELLM__MAX_CONCURRENCY=${GUIDELLM__MAX_CONCURRENCY}" > /guide-llm/${OUTPUT_PATH}/cmd
              echo "GUIDELLM__REQUEST_TIMEOUT=${GUIDELLM__REQUEST_TIMEOUT}" >> /guide-llm/${OUTPUT_PATH}/cmd
              echo "exec guidellm benchmark \
                --target "http://llm-d-inference-gateway-istio.varun-llm-d-wide-ep.svc.cluster.local" \
                --rate-type constant \
                --max-requests "${NUM_REQUESTS}" \
                --rate "1024" \
                --data '{"prompt_tokens": ${INPUT_LEN}, 
                         "output_tokens": ${OUTPUT_LEN}}' \
                --output-path "/guide-llm/${OUTPUT_PATH}/${JOB_COMPLETION_INDEX}.json" \
                --output-sampling 500 \
                --disable-console-outputs \
                --disable-progress" >> /guide-llm/${OUTPUT_PATH}/cmd


              
              exec guidellm benchmark \
                --target "http://llm-d-inference-gateway-istio.varun-llm-d-wide-ep.svc.cluster.local" \
                --rate-type constant \
                --max-requests "${NUM_REQUESTS}" \
                --rate "1024" \
                --data '{"prompt_tokens": ${INPUT_LEN}, 
                         "output_tokens": ${OUTPUT_LEN}}' \
                --output-path "/guide-llm/${OUTPUT_PATH}/${JOB_COMPLETION_INDEX}.json" \
                --output-sampling 500 \
                --disable-console-outputs \
                --disable-progress

          env:
            - name: GUIDELLM__MAX_CONCURRENCY
              value: "${MAX_CONCURRENCY}"
            - name: GUIDELLM__REQUEST_TIMEOUT
              value: "900"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HF_TOKEN
                  optional: true
          volumeMounts:
            - name: guide-llm
              mountPath: /guide-llm

      volumes:
        - name: guide-llm
          persistentVolumeClaim:
            claimName: guide-llm
